supabase:
  url: @supabase.url@
  anon: @supabase.anon.key@
  jwt_secret: @supabase.jwt.signer@
spring:
  application:
    name: Demo
  main:
    banner-mode: "off"
  datasource:
    url: @supabase.database.url@
    username: @supabase.database.user@
    password: @supbase.database.password@
    driverClassName: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/public/
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
      #show-sql: true
server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
  address: localhost
  port: ${PORT:8080}
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %yellow(%logger{40}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
  level:
    root: WARN
  org:
    hibernate:
      dialect: INFO
    springframework:
      boot:
        test:
          context:
            SpringBootTestContextBootstrapper: WARN
      test:
        context:
          support:
            AbstractContextLoader: OFF
            AnnotationConfigContextLoaderUtils: OFF
    zaxxer:
      hikari:
        HikariDataSource: INFO
